using System;

namespace AutodeskAutomation.Models.Documents
{
    public class ErrorLogDocument
    {
        // ID auto-generated by RavenDB: errorlogs/{id}
        public string Id { get; set; } = null!;
        public string UserEmail { get; set; } = null!;
        public string Platform { get; set; } = "bim360";
        public string? RunId { get; set; }
        public string? ProjectId { get; set; }
        public string? ProjectName { get; set; }
        public string? ErrorMessage { get; set; }
        public string? ScreenshotPath { get; set; }
        public DateTime LoggedAt { get; set; } = DateTime.UtcNow;
    }
}
