using System;

namespace AutodeskAutomation.Models.Documents
{
    public class ExportRunDocument
    {
        // ID auto-generated by RavenDB: exportruns/{id}
        public string Id { get; set; } = null!;
        public string UserEmail { get; set; } = null!;
        public string Platform { get; set; } = null!;
        public DateTime StartedAt { get; set; } = DateTime.UtcNow;
        public DateTime? CompletedAt { get; set; }
        public int Total { get; set; }
        public int Success { get; set; }
        public int NoDm { get; set; }
        public int Failed { get; set; }
        public int Skipped { get; set; }
        public int EmailsQueued { get; set; }
        public string? Note { get; set; }
    }
}
